# Start clean, remove restic installations via apt
# as they provide mostly outdated versions

- name: Remove restic installed via apt
  ansible.builtin.apt:
    name: restic
    state: absent
    autoremove: false
  when: ansible_facts['pkg_mgr'] == 'apt'
