---

- name: Install requirements
  ansible.builtin.package:
    name:
      # Bzip2 is needed to decompress the binary
      - bzip2
      # Fuse is needed to mount snapshots for restore
      - fuse
    state: present
  become: true
